alias c='clear'
alias cd..='cd ..'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lAhF --color=auto'
alias ls='ls --color=auto'
alias aliases='nano ~/.bash_aliases ; source ~/.bash_aliases'
alias cl='c ; ll'
